export enum TechStackLogo {
  VSCODE = "/techstack-logo/vscode_logo.png",
  GITHUB = "/techstack-logo/github_logo.png",
  FIGMA = "/techstack-logo/figma_logo.png",
  JAVA = "/techstack-logo/java_logo.png",
  SPRING_BOOT = "/techstack-logo/springboot_logo.png",
  C_SHARP = "/techstack-logo/c_sharp_logo.png",
  REACT = "/techstack-logo/react_logo.png",
  POSTGRESQL = "/techstack-logo/postgresql_logo.png",
  MYSQL = "/techstack-logo/mysql_logo.png",
  GIT = "/techstack-logo/git_logo.png",
  DOCKER = "/techstack-logo/docker_logo.png",
  AZURE = "/techstack-logo/azure_logo.png",
  AWS = "/techstack-logo/aws_logo.png",
  Intellij = "/techstack-logo/intellij_logo.png",
}

export enum TechStackName {
  VSCODE = "VS Code logo",
  GITHUB = "GitHub logo",
  FIGMA = "Figma logo",
  JAVA = "Java logo",
  SPRING_BOOT = "Spring Boot logo",
  C_SHARP = "C# logo",
  REACT = "React logo",
  POSTGRESQL = "PostgreSQL logo",
  MYSQL = "MySQL logo",
  GIT = "Git logo",
  DOCKER = "Docker logo",
  AZURE = "Azure logo",
  AWS = "AWS logo",
  Intellij = "Intellij logo",
}
