export * from "./courseCard";
export * from "./courseDetail";
export * from "./instructorDetail";
export * from "./loginCard";
export * from "./otpCard";
export * from "./paymentCard";
export * from "./quotationForm";
export * from "./testimonial";
export * from "./userInfoCard";
